### PR TITLE
modified to use buildtools and build CIA

### PR DESCRIPTION
**Pull request by svanheulen**
I know using buildtools isn't ideal since they're compiled binaries but that's just for the CIA part.

### CODE REVIEW

**Comment by svanheulen** [comment]
Oops, sorry, I didn't realize there was already a pull request with CIA building. Go ahead and delete this if you don't want it.

**Comment by neagix** [comment]
Although this patch is less complex than #39, it does not build anything. I get this error:
```
output/3ds/SuperftpdIITurbo/SuperftpdIITurbo.3dsx
Cannot open SMDH file!

make: *** [output/3ds/SuperftpdIITurbo/SuperftpdIITurbo.3dsx] Error 1

```

**Comment by svanheulen** [comment]
Sorry for the slow reply.
Is that really the only output you're getting? What OS are you using?
It works fine for me when compiling in Linux.

**Comment by mtheall** [comment]
Will wait for official devkitARM support

**Comment by fincs** [comment]
I'd like to add that official devkitARM support is indeed planned and is currently in development.

**Comment by profi200** [comment]
Maybe that's just me or something but i never liked the whole buildtools stuff. Especially for 3DS hb it brings no advantage over dkA makefiles.

**Pull request closed without merging**
