### PR TITLE
Use PabloMK7's custom logo.bin

### PR DESCRIPTION
**Pull request by Jhynjhiruu**

### CODE REVIEW

**Comment by fincs** [comment]
Why isn't this logo PR'd to makerom instead of PRing it to projects?

**Comment by Jhynjhiruu** [comment]
> 
> 
> Why isn't this logo PR'd to makerom instead of PRing it to projects?

I mentioned it to jakcron in November. He said he'd do some testing and include a fix in the next version of makerom in January and I haven't heard anything else since.

**Comment by fincs** [comment]
While that is unfortunate, that is still not a valid reason to add a logo workaround to homebrew projects. That is the responsibility of makerom, not the homebrew project.

**Comment by Jhynjhiruu** [comment]
¯\_(ツ)_/¯
Once it's fixed, the change could very easily be reversed.

**Comment by mtheall** [comment]
Sorry, I reverted this PR. This change really does belong in makerom.

**Comment by Jhynjhiruu** [comment]
OK. I guess I should submit a PR over there?

**Comment by mtheall** [comment]
yes

**Comment by jakcron** [comment]
> > Why isn't this logo PR'd to makerom instead of PRing it to projects?
> 
> I mentioned it to jakcron in November. He said he'd do some testing and include a fix in the next version of makerom in January and I haven't heard anything else since.

Sorry I was struggling to find a way to install Chinese firmware to test this on any of my hardware.

**Pull request merged**
