### PR TITLE
Fixed glitch.

### PR DESCRIPTION
**Pull request by WoniMK7**
Was glitchy when appcpulimit was 30.

### CODE REVIEW

**Comment by mtheall** [comment]
This code should go inside the `#ifdef _3DS` block and needs to have the two-space indentation.

**Comment by fincs** [comment]
Also, it should be unnecessary since [latest hbmenu does this automatically](https://github.com/smealum/3ds_hb_menu/blob/master/source/main.c#L224).

**Comment by WoniMK7** [comment]
@fincs So the hbmenu release isn't up to date because it's still glitchy atm.

**Comment by mtheall** [comment]
Is this still a problem?

**Comment by WoniMK7** [comment]
Yeah but it seems it isn't in 1.1(or it's different).

**Pull request closed without merging**
