### PR TITLE
Print parsed command when it is invalid

### PR DESCRIPTION
**Pull request by m45t3r**
Helps to debug.

### CODE REVIEW

**Comment by mtheall** [comment]
I removed that as part of 920cd96c due to the addition of escaping '\r\n' in the command channel. If the user sent a command with that in it, we would send it back unescaped and lose sync with the client.

So, if you want to add it back, make sure to escape the buffer, then I can accept the change.

**Comment by m45t3r** [comment]
And now?

I am assuming that there is only one carriage return in the string. I think if there is more than one, we already have more problems.

**Comment by m45t3r** [comment]
Just using the correct naming: `\r\n` is CRLF, not CR (that would be `\r` only).

**Comment by mtheall** [comment]
I just realized that there can't be a LF or CRLF because they would be found in the delimiter search in the prior code. So what we needed to do was encode the command to escape LF. See 44f8eaf5.

**Pull request merged**
