### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by m45t3r**

### CODE REVIEW

**Comment by mtheall** [comment]
Can you remove the part about the original code by smealum? All of the code here is original.

**Comment by m45t3r** [comment]
Ok, here we go.

I thought you just modified the code from FTPony since issue #33.

**Comment by mtheall** [comment]
I didn't fork it; I made my own code base.

**Comment by m45t3r** [comment]
Yeah, sorry.

It should be ok now, though.

**Pull request merged**
