### PR TITLE
fix build with latest libnx

### PR DESCRIPTION
**Pull request by justinkb**

### CODE REVIEW

**Comment by electrus89** [comment]
I can confirm when making the same change with my copy of the repo that it compiles. It appears that libnx has removed the bsdsockets_version field, so setting that field causes an compile-time failure.

**Comment by eku** [comment]
How do you define which version of linbx is used for compilation? The change breaks the build with an older version. The code should be able to do both.

**Comment by justinkb** [comment]
@eku I'm pretty sure it's just assumed in the switch homebrew scene that you will use the latest available libnx from devkitpro, and if not, you're on your own. I don't see any defines in the libnx includes that would allow a C preprocessor to determine the libnx version easily. I may be wrong though

**Comment by electrus89** [comment]
It appears the structure affected changed with an [October commit to libnx](https://github.com/switchbrew/libnx/commit/1bb5a21453ebae17b0a5f754c83fbaa98942dc17). libnx started autodetecting the bsdsockets version with this commit, which breaks the code at issue here.

I agree with the conclusion @justinkb came to being unable to use the preprocessor directives (specifically, no defines). [There are five pages of results, but none of them refer to a preprocessor directive referring to the library version.](https://github.com/search?q=repo%3Aswitchbrew%2Flibnx+version&type=code)

**Comment by mtheall** [comment]
This is fixed in the cmake branch which will eventually be merged

**Pull request closed without merging**
