### PR TITLE
Merging lastest commits from master to cia branch

### PR DESCRIPTION
**Pull request by m45t3r**

### CODE REVIEW

**Comment by WinterMute** [comment]
Can we get rid of this branch please. This build system should be viewed with extreme prejudice given that it replaces the *standard* build system in it's entirety and *will* cause problems with future devkitARM updates.

**Comment by m45t3r** [comment]
"Standard build system" is just a bunch of Makefiles. Buildtools does source the same `3ds_rules` file from devkitARM, and if this changes both buildtools AND the "standard build system" would break. And Steivece10 is a respect member of homebrew community anyway (however, buildtools is not really a public project, so maybe he can break it if he does want).

Not that I really care, for me any way to build CIAs would work. However, just because you made it work with "standard build system" does not mean that your method is better. #39 is lacking proper credits (the folder used as a icon needs a credit, this is because it is licensed in CC-BY), and it is not proper multiplatform.

**Comment by WinterMute** [comment]
The standard build system is a little more than a bunch of Makefiles. It depends on tools provided by devkitPro which can, and do, change as required. Every "replacement" build system in the 13 year history of devkitARM has left uncompilable projects in it's wake which have caused major support issues for devkitPro.

There is currently some work in progress to produce a cia builder which doesn't majorly infringe Nintendo's copyrights and will actually be suitable for inclusion with the tools provided by devkitARM.

In the meantime, replacing the build system entirely for the sake of a couple of tools is massively inappropriate and *will* cause problems in the future.

**Comment by WinterMute** [comment]
Also, fwiw, merging changes from master into a feature branch is not an appropriate use of a pull request. Generally the feature branch should be rebased before final merge.

Doing this just ends up with "merged from master" cruft in the master history.

**Comment by m45t3r** [comment]
Those same tools that is included by DevkitPro are used by buildtools too,
and any external tool that buildtools use is used by your PR too.
Buildtools does not include external tools unless necessary (it does
include makerom/bannertool, not gcc for example). So I don't know why
you're saying this. If one day there is an official way to do CIA builds
using only DevkitPro, great, we can just change Makefile since it will be
needed to be change anyway (and this is git, we can just get the old
Makefile if this is necessary). This is not the case today.

Just to make clear: buildtools is not a build system replacement like using
CMake, it still uses Makefiles, it still import default rules from
devkitPro itself, it still uses DevkitPro tools, only includes
bannertool/makerom (which AFAIK, are both opensource, however I don't know
if the code is legal or not) and some additional rules for CIA and 3ds
files. However I may be missing something here.

And yeah, I know that the proper git etiquette would be to rebase, however
I don't know how @mtheall prefers to do it so I did a merge. If he wants a
rebase he can ask me to do it and I would do it, this is why I did a PR
anyway. PR are for request for comments on how to improve, not "please
merge or I will kill myself". I don't even know if he wants to merge this
branch in master someday. AFAIK, he just want a separate branch that
supports building CIA.

And if we are talking about what is proper to do on GitHub anyway, I think
talking about how integrating buildtools was a bad idea would be better
discussed in your PR, not in this one that is unrelated to the issue (I am
just merging the last fixes in a branch that is already accept).

**Comment by WinterMute** [comment]
The tools are produced *by* devkitPro. devkitPro is the entity which produces devkitARM.

buildtools *does not* import default rules from the devkitPro supplied build system. It replaces the devkitPro supplied build system in it's entirety.

**Pull request closed without merging**
