### PR TITLE
New HOME Menu music

### PR DESCRIPTION
**Pull request by SoulRepo**
The current audio used is pretty bland, so here's a simple soundbite you can use.

### CODE REVIEW

**Comment by fincs** [comment]
Is the file corrupted? I only hear strange faint clicking noises.

**Comment by SoulRepo** [comment]
> Is the file corrupted? I only hear strange faint clicking noises.
Yeah, it looks like nothing's changed. I guess it's corrupted. Since I have a trial on FL Studio, I'm gonna have to make a new one. Wait a bit, then I'll update.

**Comment by SoulRepo** [comment]
There we go. No more boomer version.

**Comment by mtheall** [comment]
Just sounds like a few clicks to me too

**Pull request closed without merging**
